<a href="https://colab.research.google.com/github/lgplorea/EjerciciosPython/blob/main/ejerciciotablaCSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

# Lee el archivo
df = pd.read_csv('ventas.csv')

# Multiplica las dos columnas y guarda el resultado en una nueva llamada 'Total'
df['Total'] = df['precio'] * df['unidades']

# Verificamos que la nueva columna aparezca al final
df.head(10)

        fecha    producto  precio  unidades  Total
0  2024-01-01    Camiseta      20         5    100
1  2024-01-02    Pantalón      30         2     60
2  2024-01-03    Camiseta      20         3     60
3  2024-01-04  Zapatillas      50         1     50
4  2024-01-05    Pantalón      30         4    120
5  2024-01-06    Sudadera      35         2     70
6  2024-01-07  Zapatillas      50         2    100
7  2024-01-08    Camiseta      20         6    120
8  2024-01-09    Pantalón      30         1     30
9  2024-01-10    Sudadera      35         3    105

In [34]:
# Agrupar por producto y sumar ingresos
# 3. Agrupamos por 'producto', sumamos la columna 'Total' y reiniciamos el índice
ingresos_por_producto = df.groupby('producto')['Total'].sum().reset_index()

# 4. Cambiamos el nombre de la columna para que se entienda mejor el resultado
ingresos_por_producto = ingresos_por_producto.rename(columns={'Total': 'Ingresos_Totales'})

# 5. Ordenamos los productos de mayor a menor ingreso
ingresos_por_producto = ingresos_por_producto.sort_values(by='Ingresos_Totales', ascending=False)

ingresos_por_producto

     producto  Ingresos_Totales
0    Camiseta               280
1    Pantalón               210
2    Sudadera               175
3  Zapatillas               150

In [30]:
# Convierte la columna fecha a tipo datetime
df['fecha'] = pd.to_datetime(df['fecha'])

# Verificamos el resultado
print(df.head(10))

       fecha    producto  precio  unidades  Total nombre_mes      mes
0 2024-01-01    Camiseta      20         5    100 2024-01-01  January
1 2024-01-02    Pantalón      30         2     60 2024-01-02  January
2 2024-01-03    Camiseta      20         3     60 2024-01-03  January
3 2024-01-04  Zapatillas      50         1     50 2024-01-04  January
4 2024-01-05    Pantalón      30         4    120 2024-01-05  January
5 2024-01-06    Sudadera      35         2     70 2024-01-06  January
6 2024-01-07  Zapatillas      50         2    100 2024-01-07  January
7 2024-01-08    Camiseta      20         6    120 2024-01-08  January
8 2024-01-09    Pantalón      30         1     30 2024-01-09  January
9 2024-01-10    Sudadera      35         3    105 2024-01-10  January

In [29]:
# Agrupa por mes y producto
resumen = (
    df.groupby(['mes', 'producto'])
      .agg({
          'unidades': 'sum',
          'Total': 'sum'
      })
      .reset_index()
)

print(resumen)

       mes    producto  unidades  Total
0  January    Camiseta        14    280
1  January    Pantalón         7    210
2  January    Sudadera         5    175
3  January  Zapatillas         3    150